codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "lib/core/error"
  - "lib/core/widget"
  - "lib/core/module"
  - "lib/core/entities"
  - "api_key.dart"
  - "color_collection.dart"
  - "injection.dart"
  - "injection.iconfig.dart"
  - "lib/features/movie/features/discover_movie/data/models/discover_movie_model.freezed.dart"
  - "lib/features/movie/features/discover_movie/domain/entities"
  - "lib/features/movie/features/discover_movie/presentation/bloc/discover_movie_bloc.freezed.dart"
  - "lib/features/movie/features/discover_movie/presentation/pages"
  - "lib/features/movie/features/discover_movie/presentation/widgets"
  - "lib/features/movie/features/detail_movie/domain/entities"
  - "lib/features/movie/features/detail_movie/data/models/detail_movie_model.freezed.dart"
  - "lib/features/movie/features/detail_movie/presentation/bloc/detail_movie_bloc.freezed.dart"
  - "lib/features/movie/features/detail_movie/presentation/pages"
  - "lib/features/movie/features/detail_movie/presentation/widgets"


